name: UPDATE-MAILLES

on:
  #schedule:
    #- cron:  '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - shell: powershell
      - name: Script
        run: |
          ./RECHERCHE.ps1
