name: SEARCH-2019

on:
  #schedule:
    #- cron:  '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Script
        run:  |
          ./SCRIPTS/SEARCH-2019.ps1
